services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_DSN: postgres://postgres:postgres@db:5432/era?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: era
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    migrate:
    image: postgres:16
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: era
    volumes:
      - ./db/migrations:/migrations:ro
    command: >
      bash -e -c "
        until pg_isready -h db -U $POSTGRES_USER -d $POSTGRES_DB; do
          echo 'waiting for db...'; sleep 1;
        done;
        for f in /migrations/*.sql; do
          echo Running $f;
          PGPASSWORD=$POSTGRES_PASSWORD psql \
            -h db -U $POSTGRES_USER -d $POSTGRES_DB \
            -v ON_ERROR_STOP=1 -f \"$f\";
        done;
        echo 'Migrations done'
      "

volumes:
  pgdata:
