version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: era
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d era"]
      interval: 3s
      timeout: 3s
      retries: 30
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_DSN: postgres://postgres:postgres@db:5432/era?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  migrate:
    image: postgres:16-alpine
    depends_on:
      db:
        condition: service_healthy
    working_dir: /workspace
    environment:
      PGHOST: db
      PGPORT: "5432"
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: era
    volumes:
      - ./:/workspace:ro
    command: ["sh", "-c", "chmod +x db/migrate.sh && db/migrate.sh"]

volumes:
  db-data: {}
