services:
  postgres-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: era_test
      POSTGRES_USER: era
      POSTGRES_PASSWORD: era
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U era -d era_test"]
      interval: 3s
      timeout: 3s
      retries: 30
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

volumes:
  postgres-test-data:
