name: CI

# Disabled - using test.yml for comprehensive CI
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: era
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres -d era"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5
    env:
      DB_DSN: postgres://postgres:postgres@localhost:5432/era?sslmode=disable
      JWT_SECRET: supersecret
      JWT_ISS: era-inventory-api
      JWT_AUD: era-inventory-api
      RLS_ENABLED: "false"  # enable later if tests set GUC per request
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Go tidy
        run: go mod tidy
      - name: Run migrations
        run: |
          # simple loop to apply SQL files with psql
          for f in db/migrations/*.sql; do
            [ -e "$f" ] || continue
            psql "$DB_DSN" -v ON_ERROR_STOP=1 -f "$f"
          done
      - name: Tests
        run: go test ./internal/... -v
